export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';
export const RESET_AUTHENTICATION = 'RESET_AUTHENTICATION';
export const SET_NEW_USER = "SET_NEW_USER";
export const REGISTRATION_COMPLETED = "REGISTRATION_COMPLETED";
export const CHECK_AUTHENTICATION = "CHECK_AUTHENTICATION";